version: 0.1
phases:
  install:
    # runtime-versions:
    #     nodejs: 10
#   build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket ev-world-aws-lambda-bucket --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml