version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - python --version
      # - pip install amazon-dax-client
      - aws cloudformation package --template-file template.yml --s3-bucket ev-world-aws-lambda-bucket --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
