AWSTemplateFormatVersion: '2010-09-09'
Description: A sample application showing how to use Amazon DynamoDB Accelerator (DAX) with AWS Lambda and AWS CloudFormation.
Transform: AWS::Serverless-2016-10-31

Resources:
    siteFunction:
    Type: AWS::Serverless::Function
    Properties:
        Handler: car-model-search.lambda_handler
        Runtime: python3.8
        CodeUri: ./services
        Events:
            getUrl:
                Type: Api
                Properties:
                    Method: get
                    Path: /{id+}
            postUrl:
                Type: Api
                Properties:
                    Method: post
                    Path: /car-model-search
        Policies:
            - AmazonDynamoDBFullAccess
            - AWSLambdaVPCAccessExecutionRole
        Timeout: 10

