#SAM Template - defines the application
#AWS SAM is a model used to define serverless applications on AWS
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CD Demo Lambda
Resources:
    #Defining the lambda function for testing
    CDDemoLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambdaFunction.lambda_handler
            Runtime: python3.8
            CodeUri: ./services
            Description: 'Lambda function for CD Demo'
            MemorySize: 128
            Timeout: 30
            Role: arn:aws:iam::322967638274:role/custom-lambda-role
            Events:
                getAZsAPI:
                    Type: Api
                    Properties:
                        Path: /getazs
                        Method: post
            Environment:
                Variables:
                    REGION: ap-southeast-1
    
    #search model lambda function
    ModelSearchLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: car-model-search.lambda_handler
            Runtime: python3.8
            CodeUri: ./services
            Description: 'Lambda function for car model search'
            MemorySize: 128
            Timeout: 30
            Role: arn:aws:iam::322967638274:role/custom-lambda-role
            Events:
                scanCarModelAPI:
                    Type: Api
                    Properties:
                        Path: /car-model-search
                        Method: post
            Environment:
                Variables:
                    REGION: ap-southeast-1
    
    #retrieve price lambda function
    PriceRetrievalLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: car-price-retrieval.lambda_handler
            Runtime: python3.8
            CodeUri: ./services
            Description: 'Lambda function for car price retrieve'
            MemorySize: 128
            Timeout: 30
            Role: arn:aws:iam::322967638274:role/custom-lambda-role
            Events:
                getCarPriceAPI:
                    Type: Api
                    Properties:
                        Path: /car-price
                        Method: post
            Environment:
                Variables:
                    REGION: ap-southeast-1                

    #retrieve options lambda function
    OptionsRetrievalLambda:
        Type: AWS::Serverless::Function
        Properties:
            Handler: car-option-retrieval.lambda_handler
            Runtime: python3.8
            CodeUri: ./services
            Description: 'Lambda function for car options retrieve'
            MemorySize: 128
            Timeout: 30
            Role: arn:aws:iam::322967638274:role/custom-lambda-role
            Events:
                getCarOptionsAPI:
                    Type: Api
                    Properties:
                        Path: /car-options
                        Method: post
            Environment:
                Variables:
                    REGION: ap-southeast-1
